### ISSUE TITLE
test_form failed with treq 20.4.1

### ISSUE THREAD

**Issue by yan12125** [twisted/klein#339] opened 2020-04-26 07:11 UTC
I'm the maintainer of Arch Linux package [python-klein](https://www.archlinux.org/packages/community/any/python-klein/), and I run a periodic script to check compatibility among Python packages. Recently I notice tests in python-klein no longer work with python-treq 20.4.1.

Steps to reproduce:

1. Clone commit c91085d3b3a4b3521e1527fff82fa970c004eb2a of this repo
2. Change the following line to `treq==20.4.1`
https://github.com/twisted/klein/blob/c91085d3b3a4b3521e1527fff82fa970c004eb2a/tox.ini#L46

3. Run `tox -e coverage-py38-twcurrent`

Actual results:

```
[FAIL]
Traceback (most recent call last):
  File "/home/yen/tmp/klein/.tox/coverage-py38-twcurrent/lib/python3.8/site-packages/klein/test/test_form.py", line 473, in test_customParameterValidation
    self.assertTrue(errorText.endswith("'not a number'"))
  File "/home/yen/tmp/klein/.tox/coverage-py38-twcurrent/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 397, in assertTrue
    super(_Assertions, self).assertTrue(condition, msg)
  File "/usr/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: False is not true

klein.test.test_form.TestForms.test_customParameterValidation
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/yen/tmp/klein/.tox/coverage-py38-twcurrent/lib/python3.8/site-packages/klein/test/test_form.py", line 409, in test_handlingGET
    self.assertEqual(calls, [(u"hello, big world", 4321)])
  File "/home/yen/tmp/klein/.tox/coverage-py38-twcurrent/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 434, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.8/unittest/case.py", line 1118, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib/python3.8/unittest/case.py", line 1100, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [('hello, big+world', 4321.0)] != [('hello, big world', 4321)]

First differing element 0:
('hello, big+world', 4321.0)
('hello, big world', 4321)

- [('hello, big+world', 4321.0)]
?              ^            --

+ [('hello, big world', 4321)]
?              ^


klein.test.test_form.TestForms.test_handlingGET
```

Expected results: tests pass

**Comment by twm** [comment] 2020-04-27 04:33
Here's the full test on trunk:

https://github.com/twisted/klein/blob/c91085d3b3a4b3521e1527fff82fa970c004eb2a/src/klein/test/test_form.py#L392-L409

This looks like a behavioral change in treq. https://github.com/twisted/treq/pull/265/ made treq always parse URLs with hyperlink, rather than passing `bytes` URLs through.

Hyperlink seems to be percent-encoding the `+` when parsing the URL:

```py
>>> from hyperlink import parse
>>> u = parse(b"https://localhost/getme?name=hello,%20big+world&value=4321".decode('ascii'))
>>> u
DecodedURL(url=URL.from_text('https://localhost/getme?name=hello,%20big%2Bworld&value=4321'))
>>> u.to_uri().to_text().encode('ascii')
b'https://localhost/getme?name=hello,%20big%2Bworld&value=4321'
```

This seems like a bug to me. `+` in the query part should be treated like `%20`. For example, this is what the [web API](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) does:

```js
u = new URL("https://localhost/getme?name=hello,%20big+world&value=4321");
console.log(u.searchParams.get("name"));
// outputs: hello, big world
```

**Comment by dol-sen** [comment] 2020-06-01 04:02
I can confirm this same error.  But I am also getting a test fail at line 454 of test_customParameterValidation in test_form.py.  The result is        
                "'not+a+number'" for 
self.assertTrue( errorText.endswith("'not a number'") )

This sounds like the same hyperlink error

**Comment by wsanchez** [comment] 2020-06-01 04:49
Hrm. I wonder why `requires.io` hasn't generated a PR with the `treq` update yet…

**Comment by yan12125** [comment] 2020-06-02 11:20
There seems to be a bug in `requires.io`. treq 20.4.1 is released on Apr 17 [1] but the pull request created on Apr 19 [2] updated treq to 20.3.0.

[1] https://github.com/twisted/treq/releases/tag/release-20.4.1
[2] https://github.com/twisted/klein/pull/337

**Comment by wsanchez** [comment] 2020-06-02 18:17
OK I can open a PR and manually update some things, but I have a queue of PRs open that need review before I want to throw more on the pile.

**Comment by wsanchez** [comment] 2020-06-03 19:23
OK #352 will update everything else, but we'll need a resolution on a fix to this before updating `treq`.

**Comment by wsanchez** [comment] 2020-09-15 21:03
See https://github.com/python-hyper/hyperlink/issues/129 for debate as to whether this test is correct.

**Comment by twm** [comment] 2021-01-11 07:43
There was a Hyperlink release on Friday, so https://github.com/twisted/treq/pull/304 is ready for review! I'll do a treq release as soon as that's in.

**Comment by yan12125** [comment] 2021-01-11 14:13
Thanks for the update! I can confirm with hyperlink 21.0.0, all klein tests are green.

**Comment by wsanchez** [comment] 2021-02-22 18:19
Thanks! Closing.

**Closed by wsanchez** 2021-02-22 18:19 UTC
Labels: bug
