### ISSUE TITLE
Unbuntu + Debian Branches : Refuses to fully install ... @UB17.10

### ISSUE THREAD

**Issue by aspadistra** [twisted/klein#216] opened 2017-10-27 00:15 UTC
sudo aptitude 

[sudo] password for ha64: 

Performing actions...
Setting up python-klein (17.2.0-1) ...
  File "/usr/lib/python2.7/dist-packages/klein/test/py3_test_resource.py", line 26
    async def leaf(request):
        ^
SyntaxError: invalid syntax

dpkg: error processing package python-klein (--configure):

 subprocess installed post-installation script returned error exit status 101

Errors were encountered while processing:

 python-klein

E: Sub-process /usr/bin/dpkg returned an error code (1)

Setting up python-klein (17.2.0-1) ...

  File "/usr/lib/python2.7/dist-packages/klein/test/py3_test_resource.py", line 26

    async def leaf(request):
        ^
SyntaxError: invalid syntax

dpkg: error processing package python-klein (--configure):

 subprocess installed post-installation script returned error exit status 101

Errors were encountered while processing:

 python-klein

Press Return to continue, 'q' followed by Return to quit.

**Comment by rodrigc** [comment] 2017-10-27 00:50
There is nothing wrong with klein.  The problem is with the Debian packaging, where they are doing something wrong, trying to manipulate Python 3-only files on Python 2.

Someone filed a bug for this:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868570

You should follow up with Debian in that ticket.

**Comment by aspadistra** [comment] 2017-11-06 02:57
So far I have used the Synaptic Package Manager to revert to the older stable version, and put a lock on it -- however the SPM UI refers to locked packages as Pinned ... 

So crisis simi-over, but it seems that no matter what the Debian origin installer (if it has been updated since my post) still botches up Python Klein. 

Would you be willing to split the difference and assume that there may be at least some subtle bug with PK that as of the current version may only assert itself some of the time ... and that the Debian installer's bug may be interacting with your possible bug on some systems ... as my Lunbuntu-32bit-x86 installation on an EeePC (ASUS) does not seem to have this horrific glitch ...

**Comment by twm** [comment] 2017-11-08 05:45
I'm closing this issue as it doesn't seem to represent any work that needs doing on Klein itself, and the linked Debian bug has been closed. If the python-klein package still fails to install, please follow up with the Debian folks.

**Closed by twm** 2017-11-08 05:45 UTC

**Comment by aspadistra** [comment] 2017-12-09 03:21
Until your Debian bugfix is propagated, and with Unbuntu 17.10 is has not (as of the time of this posting) the bug will continue to snarl [among other things] Synaptic Package Manager from being able to fully clean out the residue of previous installations. 

Still there probably have been worse bugs so only a temporary SNAFU ... so hope for it being done by the 99th Day of Christmas ...

**Comment by aspadistra** [comment] 2017-12-12 08:02
The bugfix has hit 32 bit LUBNUNTU 17.10, but has not arrived at the 64 bit versions of standard UNBUNTU ... so I assume higher up the Debian tree the fix for this problem is live as of me posting this.
